#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: My Resume
url: 'https://priteshbhole.github.io'
baseurl: '/resume'
description: A beautiful Jekyll theme for creating resume
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: turquoise # blue turquoise green berry orange ceramic
chrome_mobile_color:

# Tracker
analytics: UA-83979019-1



# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4000
host: 0.0.0.0
safe: false
